import Head from 'next/head';
import Slider from "../components/Slider/Slider";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Xplode task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider />     
    </div>
  )
}
