import Head from 'next/head';
import { useEffect } from 'react';
import styles from '../styles/Home.module.scss';
import Main from '../components/Todos/Todos';

export const getStaticProps = async () => {
  const fetchData:any = await fetch("http://localhost:3000/api/getTodos");
  const data = await fetchData.json();
  const todos:any[] = [];
  if(data.length > 0){
    for( let x of data) {
      todos.push(x);
   };
  };
  return {
    props: {
      todos
    }
  }
};

export default  function Home({todos}:any) {

  return (
    <div className={`${styles.container} ${styles.main}`}>
      <Head>
        <title>Todos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main todos={todos}/>
    </div>
  )
};
